#!/bin/bash

echo "🎯 Complete Guide: Making Jeff Human-Like"
echo "========================================"
echo ""
echo "Follow these steps IN ORDER for best results:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📍 STEP 1: VOICE SETTINGS (11Labs)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Go to Voice section and adjust:"
echo ""
echo "☐ Provider: 11labs"
echo "☐ Voice: Try these (in order of preference):"
echo "   1. Adam (pNInz6obpgDQGcFmaJgB) - Warm, friendly"
echo "   2. Antoni (ErXwobaYiN019PkySvjV) - Professional"
echo "   3. Josh (TxGEqnHWrfWFTfGW9XjX) - Casual"
echo ""
echo "☐ Stability: 0.65 (natural variation)"
echo "☐ Clarity: 0.75"
echo "☐ Speed: 0.95 (slightly slower = more natural)"
echo "☐ Style: 0.2 (adds emotion)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📍 STEP 2: TRANSCRIBER (Critical!)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "☐ Provider: OpenAI (handles natural speech better)"
echo "☐ Model: gpt-4o-transcribe"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📍 STEP 3: ADVANCED SETTINGS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "☐ Smart Endpointing: Vapi (NOT LiveKit)"
echo ""
echo "☐ Start Speaking Plan:"
echo "   • Wait seconds: 0.7"
echo "   • Transcription Cutoff: 0.3"
echo ""
echo "☐ Stop Speaking Plan:"
echo "   • Voice seconds: 0.4"
echo "   • Back off seconds: 1.8"
echo ""
echo "☐ Idle Messages:"
echo "   • Delay: 8 seconds"
echo "   • Messages: "
echo '     ["Still there?", "You okay?", "Take your time..."]'
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📍 STEP 4: MODEL SETTINGS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "☐ Temperature: 0.7 (more creative/human)"
echo "☐ Max Tokens: 150 (shorter, natural responses)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📍 STEP 5: FIRST MESSAGE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Replace with something warmer:"
echo ""
echo '"Hey there! This is Jeff. I help folks tackle credit card debt,"'
echo '"and I know talking about money stuff can be tough. How are you doing today?"'
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📍 STEP 6: SYSTEM PROMPT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Copy the content from: jeff-human-system-prompt.txt"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ SAVE & TEST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Click SAVE at bottom of page"
echo "2. Test with: ./test-call.sh +16476278084"
echo ""
echo "🎭 WHAT TO EXPECT:"
echo "• Natural pauses between exchanges"
echo "• Varied speech patterns"
echo "• Emotional reactions to what you say"
echo "• Smooth conversation flow"
echo "• No robotic repetition"
echo "" 