#!/bin/bash

echo "🧑 Making Jeff Sound Human & Natural"
echo "===================================="
echo ""
echo "Let's transform Jeff from robotic to truly human!"
echo ""
echo "🎯 COMPLETE HUMAN-LIKE SETTINGS:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1️⃣ VOICE SETTINGS (11Labs)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "• Voice: Adam (pNInz6obpgDQGcFmaJgB)"
echo "• Stability: 0.65 (more natural variation)"
echo "• Similarity: 0.75 (balanced)"
echo "• Style: 0.2 (slight emotion)"
echo "• Speed: 0.95 (slightly slower)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "2️⃣ CONVERSATION FLOW SETTINGS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TRANSCRIBER:"
echo "• Provider: OpenAI (best for natural speech)"
echo "• Model: gpt-4o-transcribe"
echo ""
echo "SMART ENDPOINTING:"
echo "• Set to: Vapi (not LiveKit)"
echo ""
echo "START SPEAKING PLAN:"
echo "• Wait seconds: 0.7 (natural pause)"
echo "• Transcription Cutoff: 0.3"
echo ""
echo "STOP SPEAKING PLAN:"
echo "• Voice seconds: 0.4"
echo "• Back off seconds: 1.8"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "3️⃣ HUMAN-LIKE SYSTEM PROMPT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Copy this enhanced prompt to Jeff's System Prompt: 