#!/bin/bash

echo "🤖 Optimizing Jeff with Gemini Settings"
echo "======================================="
echo ""
echo "Current: Google Gemini 2.5 Flash"
echo "Let's optimize for better conversation flow!"
echo ""
echo "📋 RECOMMENDED CHANGES:"
echo ""
echo "1️⃣ MODEL SETTINGS:"
echo "   • Provider: Google (keep)"
echo "   • Model: Try 'Gemini 2.0 Flash' (more stable)"
echo "   • Max Tokens: Increase to 500 (from 250)"
echo "   • Temperature: Lower to 0.3 (from 0.5)"
echo ""
echo "2️⃣ SMART ENDPOINTING:"
echo "   • Set to: Off or Vapi"
echo "   • Avoid LiveKit with Gemini"
echo ""
echo "3️⃣ TIMING SETTINGS:"
echo "   • Wait seconds: 0.5"
echo "   • Voice seconds: 0.3" 
echo "   • Back off seconds: 1.0"
echo ""
echo "4️⃣ SYSTEM PROMPT TWEAK:"
echo "   Add this at the TOP of system prompt:"
echo "   'CRITICAL: Always pause for 1 full second"
echo "   before responding. Count: one-mississippi.'"
echo ""
echo "💡 WHY THESE CHANGES:"
echo "• Lower temperature = more consistent responses"
echo "• Higher token limit = complete thoughts"
echo "• Explicit pause instruction = better timing"
echo ""
echo "🚨 ALTERNATIVE: Try OpenAI GPT-4"
echo "If Gemini still has timing issues, consider:"
echo "• Provider: OpenAI"
echo "• Model: gpt-4-turbo"
echo "• Better at following interruption rules" 