#!/bin/bash

echo "🔧 Jeff's Quick Manual Fix Checklist"
echo "===================================="
echo ""
echo "Follow these steps in order:"
echo ""
echo "📍 Step 1: Open Vapi Dashboard"
echo "   → https://dashboard.vapi.ai/assistants"
echo "   → Click on 'Jeff'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 Step 2: TRANSCRIBER Settings"
echo "   → Scroll to 'Transcriber' section"
echo "   → Click 'Advanced Settings'"
echo "   → Change these:"
echo ""
echo "   ☐ Smart Endpointing = ON ✅"
echo "   ☐ End of Speech Threshold = 1500ms"
echo "   ☐ Speech Detection Sensitivity = 0.3"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 Step 3: VOICE Settings"  
echo "   → Scroll to 'Voice' section"
echo "   → Click 'Advanced Settings'"
echo "   → Change these:"
echo ""
echo "   ☐ Interruption Sensitivity Override = ON ✅"
echo "   ☐ Interruption Sensitivity = 0.8"
echo "   ☐ Background Noise Suppression = ON ✅"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 Step 4: SAVE"
echo "   → Click 'Save' button at bottom"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 Step 5: TEST"
echo "   → Run: ./test-call.sh +16476278084"
echo "   → Try pausing mid-sentence"
echo "   → Jeff should wait patiently!"
echo ""
echo "🎯 That's it! These 4 settings will fix 90% of interruption issues."
echo ""
echo "Still interrupting? Try:"
echo "• Interruption Sensitivity = 0.9 (super patient)"
echo "• End of Speech Threshold = 2000ms (2 full seconds)"
echo ""
echo "Press Enter to open the dashboard..."
read -p ""
open "https://dashboard.vapi.ai/assistants" 