services:
  - type: web
    name: vapi-customer-service
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
      - key: VAPI_PRIVATE_KEY
        sync: false # Set this in Render dashboard for security
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_EMAIL
        sync: false # Set this in Render dashboard
      - key: SMTP_PASSWORD
        sync: false # Set this in Render dashboard for security
      - key: SMTP_FROM_NAME
        sync: false # Set this in Render dashboard
      - key: DEFAULT_MEETING_LINK
        sync: false # Set this in Render dashboard
      - key: SERVER_URL
        sync: false # This will be your Render URL
    autoDeploy: false
