#!/bin/bash

echo "🔄 Resetting Jeff to Reliable Default Settings"
echo "=============================================="
echo ""
echo "The experimental settings made things worse!"
echo "Let's go back to proven defaults that work."
echo ""
echo "📋 RESET TO THESE SETTINGS:"
echo ""
echo "1️⃣ SMART ENDPOINTING:"
echo "   • Set to: Off (or Vapi if Off isn't available)"
echo "   • LiveKit seems to cause issues"
echo ""
echo "2️⃣ START SPEAKING PLAN:"
echo "   • Wait seconds: 0.6 (middle ground)"
echo ""
echo "3️⃣ STOP SPEAKING PLAN:"
echo "   • Voice seconds: 0.4 (not max)"
echo "   • Back off seconds: 1.5"
echo ""
echo "4️⃣ TRANSCRIBER:"
echo "   • Keep OpenAI GPT-4o (it's working fine)"
echo ""
echo "These are conservative settings that should:"
echo "• Prevent interruptions"
echo "• Avoid awkward long pauses"
echo "• Keep conversation natural"
echo ""
echo "🚨 If still having issues after this reset:"
echo "Consider switching the Model provider from"
echo "Google Gemini to OpenAI GPT-4 for more"
echo "consistent conversation flow." 