#!/bin/bash

# Setup Twilio + Vapi Integration for Canadian Phone Number
echo "🇨🇦 Setting up Jeff's Canadian phone number with Twilio + Vapi..."
echo ""

echo "📋 STEP 1: Create Twilio Account (5 minutes)"
echo "1. Go to https://www.twilio.com/try-twilio"
echo "2. Sign up for free account"
echo "3. Add $20 CAD to your account"
echo "4. Navigate to Phone Numbers → Manage → Buy a number"
echo "5. Choose Canadian number:"
echo "   • Toronto: +1-416-XXX-XXXX or +1-647-XXX-XXXX"
echo "   • Vancouver: +1-604-XXX-XXXX or +1-778-XXX-XXXX"
echo "   • Montreal: +1-514-XXX-XXXX or +1-438-XXX-XXXX"
echo "   • Calgary: +1-403-XXX-XXXX or +1-587-XXX-XXXX"
echo "6. Purchase the number (Monthly cost: $1.15 CAD)"
echo ""

echo "🔑 STEP 2: Get Twilio Credentials (2 minutes)"
echo "1. Go to Twilio Console → Account → API Keys & Tokens"
echo "2. Copy these values:"
echo "   • Account SID: ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
echo "   • Auth Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
echo "   • Your Canadian Phone Number: +1XXXXXXXXXX"
echo ""

echo "🔗 STEP 3: Configure Vapi SIP Integration (5 minutes)"
echo "1. Go to https://dashboard.vapi.ai"
echo "2. Navigate to 'Phone Numbers' → 'Telephony Integrations'"
echo "3. Click 'Add Integration' → Select 'Custom SIP Trunk'"
echo "4. Fill in the details:"
echo "   • Provider: Twilio"
echo "   • SIP Gateway: sip.twilio.com"
echo "   • Username: Your Twilio Account SID"
echo "   • Password: Your Twilio Auth Token"
echo "   • Phone Number: Your Canadian number"
echo "5. Click 'Save' and 'Test Connection'"
echo ""

echo "⚙️ STEP 4: Update Jeff's Assistant (3 minutes)"
echo "1. In Vapi Dashboard, go to 'Assistants'"
echo "2. Select Jeff's assistant"
echo "3. Update 'Phone Number' to your new Canadian number"
echo "4. Update 'System Message' to mention he's calling from Canada"
echo "5. Save changes"
echo ""

echo "📞 STEP 5: Test the Canadian Number (1 minute)"
echo "1. Use this test call command:"
echo "   ./test-jeff-call.sh +16476278084"
echo "2. Jeff should now call FROM your Canadian number"
echo "3. No more 'international calling' restrictions!"
echo ""

echo "✅ FINAL RESULT:"
echo "Before: Jeff (US +16313189205) → You (+16476278084) ❌ BLOCKED"
echo "After:  Jeff (CA +1647XXXXXXX) → You (+16476278084) ✅ WORKS!"
echo ""

echo "💰 MONTHLY COSTS:"
echo "• Twilio Canadian Number: $1.15 CAD/month"
echo "• Per-minute calling: $0.0140 CAD/minute"
echo "• Total for 100 minutes: ~$2.50 CAD/month"
echo ""
echo "🎉 Jeff will now have his own Canadian business number!" 