#!/bin/bash

echo "💰 STT Models Ranked by Cost (Cheapest to Most Expensive)"
echo "========================================================"
echo ""
echo "Based on hourly usage (60 minutes):"
echo ""
echo "1️⃣ OpenAI gpt-4o-mini-transcribe 🥇"
echo "   💵 $0.24/hour ($0.004/minute)"
echo "   ✅ Good accuracy, handles names well"
echo "   ⚡ 80-150ms latency"
echo "   🎯 Best value for money"
echo ""
echo "2️⃣ OpenAI gpt-4o-transcribe 🥈" 
echo "   💵 $0.36/hour ($0.006/minute)"
echo "   ✅ BEST accuracy, perfect for names"
echo "   ⚡ 100-200ms latency"
echo "   🎯 Jeff's current choice ⭐"
echo ""
echo "3️⃣ Google Cloud Speech"
echo "   💵 $0.54/hour ($0.009/minute)"
echo "   ✅ Good multilingual support"
echo "   ⚡ 100-200ms latency"
echo "   ❌ Requires GCP setup"
echo ""
echo "4️⃣ Deepgram (nova-2 or nova-2-phonecall)"
echo "   💵 $0.59/hour ($0.0098/minute)"
echo "   ✅ Fastest response (50-100ms)"
echo "   ❌ Poor with Indian/complex names"
echo "   🎯 Default in Vapi"
echo ""
echo "5️⃣ Azure Speech Services / Assembly AI 🥉"
echo "   💵 $0.60/hour ($0.01/minute)"
echo "   ✅ Enterprise features (Azure)"
echo "   ✅ Detailed transcripts (Assembly)"
echo "   ⚡ 100-400ms latency"
echo ""
echo "📊 COST COMPARISON CHART:"
echo "┌─────────────────────────┬────────────┬────────────┐"
echo "│ Provider                │ Per Hour   │ Per Month* │"
echo "├─────────────────────────┼────────────┼────────────┤"
echo "│ OpenAI 4o-mini         │ $0.24      │ $24.00     │"
echo "│ OpenAI 4o ⭐           │ $0.36      │ $36.00     │"
echo "│ Google Cloud           │ $0.54      │ $54.00     │"
echo "│ Deepgram               │ $0.59      │ $59.00     │"
echo "│ Azure/Assembly         │ $0.60      │ $60.00     │"
echo "└─────────────────────────┴────────────┴────────────┘"
echo "*Based on 100 hours/month usage"
echo ""
echo "💡 KEY INSIGHTS:"
echo "• OpenAI 4o-mini is 60% cheaper than Deepgram"
echo "• OpenAI 4o is 40% cheaper than Deepgram"
echo "• Yet OpenAI models are MORE accurate!"
echo ""
echo "🎯 RECOMMENDATIONS:"
echo ""
echo "FOR BUDGET-CONSCIOUS:"
echo "→ Use OpenAI gpt-4o-mini-transcribe"
echo "  Still better than Deepgram at 60% the cost!"
echo ""
echo "FOR BEST ACCURACY (Jeff):"
echo "→ Use OpenAI gpt-4o-transcribe ⭐"
echo "  Worth extra $0.12/hour for perfect names"
echo ""
echo "FOR SPEED-CRITICAL:"
echo "→ Use Deepgram nova-2-phonecall"
echo "  50ms latency but poor accuracy"
echo ""
echo "📈 MONTHLY COST FOR JEFF (100 hours):"
echo "• Current (OpenAI 4o): $36/month"
echo "• If switched to mini: $24/month (save $12)"
echo "• Original (Deepgram): $59/month (save $23!)" 