#!/bin/bash

echo "🔄 Switching Jeff to OpenAI Transcriber"
echo "======================================"
echo ""
echo "OpenAI handles emails MUCH better than Deepgram!"
echo ""
echo "📋 QUICK STEPS:"
echo ""
echo "1. Go to Vapi Dashboard → Jeff → TRANSCRIBER"
echo ""
echo "2. Change Provider to: OpenAI"
echo ""
echo "3. Model: gpt-4o-transcribe (keep this)"
echo ""
echo "4. Keep these interruption settings:"
echo "   • Smart Endpointing: Off or Vapi"
echo "   • Wait seconds: 0.6-0.8"
echo "   • Voice seconds: 0.4"
echo "   • Back off seconds: 1.5"
echo ""
echo "✅ This should fix email capture issues!"
echo ""
echo "Cost difference:"
echo "• Deepgram: ~$0.0075/min"
echo "• OpenAI: ~$0.06/min (8x more but worth it for accuracy)" 