#!/bin/bash

echo "🎯 Testing Jeff with Updated OpenAI Transcription"
echo "================================================"
echo ""
echo "✅ Changes Made:"
echo "• Switched from Deepgram to OpenAI gpt-4o-transcribe"
echo "• Better accuracy for names and spelling"
echo "• Ready to handle Indian/International names"
echo ""
echo "📞 To test the improved transcription:"
echo "1. Run: ./test-call.sh YOUR_PHONE_NUMBER"
echo "2. When Jeff asks for email, spell it out slowly"
echo "3. Notice improved accuracy!"
echo ""
echo "💡 Test phrases to try:"
echo "• 'My name is Shirisha Kandalai'"
echo "• 'Email is S-H-I-R-I-S-H-A at gmail'"
echo "• 'Pradeep Patel at yahoo dot com'"
echo ""
echo "🎨 Jeff's Updated Config:"
echo "• Transcriber: OpenAI gpt-4o-transcribe"
echo "• AI Model: Google Gemini 2.5 Flash"
echo "• Voice: ElevenLabs Adam"
echo "• Phone: +1 (431) 341-5863 (Manitoba)"
echo ""
echo "Ready to make more accurate calls! 🚀" 