#!/bin/bash

echo "🎤 Switching Jeff to Deepgram Transcriber"
echo "========================================="
echo ""
echo "Deepgram is often better for real-time conversations!"
echo ""
echo "📋 HOW TO SWITCH:"
echo ""
echo "1️⃣ In Vapi Dashboard → Jeff → TRANSCRIBER section"
echo ""
echo "2️⃣ Change Provider from 'OpenAI' to 'Deepgram'"
echo ""
echo "3️⃣ Deepgram Models (try in this order):"
echo "   • nova-2 (Best accuracy & speed)"
echo "   • nova (Good balance)"
echo "   • enhanced (If others don't work well)"
echo ""
echo "4️⃣ Language: Keep as 'En'"
echo ""
echo "5️⃣ Keep these settings with Deepgram:"
echo "   • Smart Endpointing: Off or Vapi"
echo "   • Wait seconds: 0.6"
echo "   • Voice seconds: 0.4"
echo "   • Back off seconds: 1.5"
echo ""
echo "💡 Why Deepgram might help:"
echo "• Better real-time processing"
echo "• More accurate pause detection"
echo "• Less likely to cause interruptions"
echo "• Handles background noise better"
echo ""
echo "🚨 If Deepgram still has issues, try:"
echo "• AssemblyAI (very accurate but slightly slower)"
echo "• Azure (Microsoft's offering)"
echo ""
echo "Click SAVE and test with: ./test-call.sh +16476278084" 